/**
 * The vendors an agent never named once, written out as an outreach list.
 *
 *   npm run never-named
 *
 * `why-not` reads why a run walked away from a vendor it weighed. This reads the harder fact: the
 * vendors it never weighed at all. Absence is the stronger measurement of the two and the cheaper
 * one, because it needs no comparison table and no marker taxonomy, only the name matcher that
 * `audit-never-named` already checks for false accusations.
 *
 * Codex cells only. Half the published cells were run by Claude Code with the operator's CLAUDE.md
 * in reach, and the site says so; a sentence we put in a stranger's inbox should rest on the half
 * that needs no caveat.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { CATEGORIES } from '../src/lib/categories'
import { SITE_URL } from '../src/lib/site'
import { certain, mentionsIn } from '../src/lib/vendors'
import { winnersOf } from './answers.mjs'

type Cell = { category: string; question: string; runs: number; tool: string; ranAt: string; answers: { run: number; text: string }[] }

const cells = (JSON.parse(readFileSync('src/data/cells.json', 'utf8')) as Cell[]).filter((cell) => cell.tool.startsWith('codex'))
// The score comes from the published corpus rather than a local copy, so the list cannot quietly
// quote a number the site no longer shows.
const corpus = (await (await fetch(`${SITE_URL}/corpus.json`)).json()) as {
  formulaVersion: string
  rows: { domain: string; total: number; measurable: number; scorecardUrl: string }[]
}

const scoreOf = new Map<string, string>()
for (const row of corpus.rows) scoreOf.set(row.domain, `${row.total}/${row.measurable} mierzalnych`)

const lines: string[] = [
  '# Never named once',
  '',
  `Generated by \`npm run never-named\` from the codex cells in \`src/data/cells.json\`.`,
  'One row per vendor an agent never mentioned in five runs of its own category.',
  '',
  'Absence is not a ranking and is not evidence the vendor is bad. It is evidence that on this',
  'question, on this date, with this agent, they were not in the room. Everything here is five runs',
  'of one model on one day, and any message quoting it has to say so.',
  '',
]

let total = 0
for (const cell of cells) {
  const category = CATEGORIES.find((candidate) => candidate.id === cell.category)
  if (!category) continue
  const texts = cell.answers.map((answer) => answer.text)
  const all = texts.join('\n')
  const named = new Set(certain(mentionsIn(all, category.domains)).map((mention) => mention.domain))
  const missing = category.domains.filter((domain) => !named.has(domain))
  if (missing.length === 0) continue

  const top = winnersOf(texts, category.domains)[0]
  const won = top ? `${top[0]} ${top[1]}/${texts.length}` : `nikt z korpusu (wszystkie ${texts.length} biegow wybraly firme spoza niego)`

  total += missing.length
  lines.push(
    `## ${category.label} (\`${category.id}\`)`,
    '',
    `**Pytanie:** ${cell.question}`,
    '',
    `**Wybrano:** ${won}. Biegow: ${texts.length}, ${cell.tool}, ${cell.ranAt}.`,
    `**Dowod publiczny:** https://letagentsin.com/c/${category.id}/runs`,
    '',
    `Nie padli ani razu (${missing.length} z ${category.domains.length}):`,
    '',
    ...missing.map((domain) => `- \`${domain}\`${scoreOf.has(domain) ? ` (skan ${scoreOf.get(domain)})` : ''}`),
    '',
  )
}

lines.push(`---`, ``, `Razem: **${total}** firm, z ${cells.length} cel codexa, przy formule skanera ${corpus.formulaVersion}.`)
writeFileSync(join('outreach', 'never-named.md'), `${lines.join('\n')}\n`)
console.log(`outreach/never-named.md: ${total} nienazwanych w ${cells.length} kategoriach`)
