/**
 * Rebuilds `outreach/targets.md` from the published corpus. It was hand-written, so it sat two
 * formula versions behind the data it claimed to be generated from, and a target list that is
 * quietly stale is worse than none: it names vendors on verdicts we have since corrected.
 *
 *   npm run targets
 *
 * Domains whose owner we have recorded as unable to buy are excluded and counted at the bottom
 * rather than silently dropped, because a list that shrinks without saying why reads as coverage.
 */
import { writeFileSync } from 'node:fs'
import { couldBuy, OWNERSHIP } from '../src/data/ownership'

type Check = { id: string; verdict: string; points: number; max: number; detail: string }
type Row = { domain: string; total: number; measurable: number; max: number; checks: Check[] }

const url = process.argv[2] ?? 'https://stackpick-f12d13a227ea.herokuapp.com/corpus.json'
const corpus = (await (await fetch(url)).json()) as { formulaVersion: string; rows: Row[] }

const at = (row: Row, id: string) => row.checks.find((check) => check.id === id)
const full = (row: Row, id: string) => {
  const check = at(row, id)
  return check !== undefined && check.points === check.max
}
const urlIn = (detail: string) => detail.match(/https?:\/\/\S+?(?=[,\s]|$)/)?.[0] ?? ''

/** The same three legs the findings page publishes, so the target list and the research agree. */
const legs = (row: Row) => [
  full(row, 'agent_entry_point') || full(row, 'oauth_dcr') || full(row, 'mcp_present'),
  full(row, 'signup_reachable'),
  (at(row, 'programmatic_provisioning')?.points ?? 0) >= 1,
]

const buyers = corpus.rows.filter((row) => couldBuy(row.domain))
const excluded = corpus.rows.filter((row) => !couldBuy(row.domain))

/** A door for a machine and no key behind it. The premise is already theirs, which is the pitch. */
const doorNoKey = buyers
  .filter((row) => full(row, 'mcp_present') && (at(row, 'programmatic_provisioning')?.points ?? 0) === 0)
  .sort((a, b) => a.domain.localeCompare(b.domain))

const oneAway = buyers
  .map((row) => ({ row, missing: legs(row).filter((met) => !met).length }))
  .filter((entry) => entry.missing === 1)
  .map((entry) => entry.row)

const signupOnly = oneAway
  .filter((row) => !full(row, 'signup_reachable'))
  .sort((a, b) => a.domain.localeCompare(b.domain))

const lines = [
  '# Target list, generated from the corpus',
  '',
  `Generated by \`npm run targets\` from ${url} at formula **${corpus.formulaVersion}**, ${corpus.rows.length} domains.`,
  'Do not edit by hand: the previous version was hand-written and sat two formula versions behind',
  'the data it claimed to come from.',
  '',
  `${excluded.length} domains are excluded because we have recorded that nobody there can buy.`,
  'Everything else is included, including vendors we know nothing about, because absence of a',
  'record is a gap in our research rather than a fact about them.',
  '',
  `## 1. Runs an MCP server and documents no way to get a key (${doorNoKey.length})`,
  '',
  'The sharpest row we have. They spent engineering time on a door for a machine, so the budget and',
  'the internal champion both already exist, and an agent still cannot get a credential. Lead with',
  'their own endpoint URL.',
  '',
  ...doorNoKey.map((row) => `- \`${row.domain}\` · ${urlIn(at(row, 'mcp_present')?.detail ?? '')}`),
  '',
  `## 2. Everything else in place, signup unreachable without a browser (${signupOnly.length})`,
  '',
  'The barrier our own agent runs kept dying at, and the most expensive one here to fix: it crosses',
  'auth, fraud and billing. Never the opening line, always the second.',
  '',
  ...signupOnly.map((row) => `- \`${row.domain}\` · ${at(row, 'signup_reachable')?.detail ?? ''}`),
  '',
  '## Excluded, and why',
  '',
  ...excluded.map((row) => {
    const owner = OWNERSHIP[row.domain]
    return `- \`${row.domain}\` · ${owner.status} · ${owner.evidence} (checked ${owner.checkedAt})`
  }),
  '',
]

writeFileSync(new URL('../outreach/targets.md', import.meta.url), `${lines.join('\n')}\n`)
console.log(
  `targets.md: ${doorNoKey.length} door-no-key, ${signupOnly.length} signup-only, ${excluded.length} excluded, formula ${corpus.formulaVersion}`,
)
